---

- name: Create a VIP, pool, pool members and nodes
  hosts: f5-test
  connection: local

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    provider:
      password: "{{ f5_password }}"
      server: "{{ ansible_host }}"
      user: "{{ f5_username }}"
      validate_certs: "{{ validate_certs }}"
      server_port: "{{ f5_server_port }}"

  tasks:
    - name: License a BIG-IP
      bigip_device_license:
        license_key: BIG-IP PD KEY XXXXX
        license_server: "license.f5net.com"
        accept_eula: yes
        provider: "{{ provider }}"
